### ISSUE TITLE
거래소와 같이 수수료 있으면 좋을듯 합니다

### ISSUE THREAD

**Issue by DetegiCE** [SieR-VR/SieR-Bot#1]
업비트 0.05%
빗썸 0.25%인데
시어 봇 데이터 업비트에서 긁어오니까 0.05%로 하죠

**Comment by SieR-VR** [comment]
수수료 추가 완료
https://github.com/SieR-VR/SieR-Bot/commit/4ced4d15f319f907f3ec3202b7949cf1b5169f80
