### ISSUE TITLE
숏 칠수있게 해주십쇼

### ISSUE THREAD

**Issue by iidx** [SieR-VR/SieR-Bot#2]
다른건 모르겠고 이건 필수입니다 ㄹㅇ

**Comment by DetegiCE** [comment]
인정합니다

**Comment by SieR-VR** [comment]
숏 칠 수 있게 해드렸습니다.
https://github.com/SieR-VR/SieR-Bot/commit/797bf973d6c6aa0352ede1cfeeb226d16b346974
