### ISSUE TITLE
혹시 이 오류는 무엇인가요.

### ISSUE THREAD

**Issue by HANYOUHA** [SieR-VR/SieR-Bot#3]
Error: ENOENT: no such file or directory, open './Private/token.json'

이 json파일을 따로 만들어야하나요?

**Comment by SieR-VR** [comment]
네. Private 폴더 내에 { "token" : (디스코드 봇 토큰) } 형식의 json을 만들어주시면 됩니다! Readme에 설명 적어놓겠습니다!

**Comment by HANYOUHA** [comment]
UnhandledPromiseRejectionWarning: TypeError: ilegalChannels.find is not a function

이 오류는 ilegalChannels.json에 어떤 형식으로 적으면 될까요?

**Comment by SieR-VR** [comment]
[] 만 적어주시면 됩니다!

**Comment by HANYOUHA** [comment]
다른 json 파일도 [] 만 적으면 될까용??

**Comment by SieR-VR** [comment]
음.. 오늘 중으로 Readme랑 Private 파일 내용물 커밋해놓겠습니다!

**Comment by SieR-VR** [comment]
> 
> 
> 다른 json 파일도 [] 만 적으면 될까용??

커밋 완료했습니다! Readme.md에 있는 설치방법대로 다시 실행해주세요!
