### ISSUE TITLE
안녕하세요 모의투자 시어봇 문의드립니다!

### ISSUE THREAD

**Issue by jennyyyy1988** [SieR-VR/SieR-Bot#5]
안녕하세요! 구글링 중 너무 좋은 봇인거 같아 다운받고 실행을 했는데, 작동하는법을 모르겠습니다.

매수 [코드1] [코드2] [양]
[코드1] 코인을 [코드2]코인 [양]만큼 매수합니다.

이 부분이 이해가 안가는데 아무리 입력해도 오류!
존재하지 않는 코인 코드: 비트코인 이런 문구만 나오네요. 어딜 수정해야 할까요?

추가로 DB연동은 어떻게 할까요 ?

**Comment by SieR-VR** [comment]
봇 구동을 할 때 코인 코드 정보를 json으로 저장하였었는데, 업비트 정보를 이용하였기 때문에 깃허브에는 올리지 않았습니다. 현재는 남아있는 자료가 없어 코드를 보고 json 포맷을 유추할 필요가 있어 보입니다..

추가로 DB 연동은 현재로써는 계획이 없습니다. 관리되고있지 않은 프로젝트이기도 하고, 제가 사용하는 봇도 아니라서요.. 혹시 관심이 있으시다면 PR 넣어주시면 반영하겠습니다..!
